const enLocale = {
  translation: {
    description: {
      h1: 'FAVORITE COMPUTER GAMES LIST',
      loading: 'Please wait. Loading data...',
      gameTitleInput: 'Game Title',
      gameTitlePlaceholder: 'Game Name',
      yearInput: 'Year',
      genreInput: 'Genre',
      genrePlaceholder: '--Please choose an option--',
      raitingInput: 'Raiting',
      developerInput: 'Developer',
      developerPlaceholder: 'Developer',
      publisherInput: 'Publisher',
      publisherPlaceholder: 'split inputs with commas',
      buttonAdd: '+ADD',
      buttonDelete: 'DELETE ITEMS',
      genreArcade: 'Arcade',
      genreAdventure: 'Adventure',
      genreFighting: 'Fighting',
      genreRacing: 'Racing',
      genreRTS: 'Real Time Strategy (RTS)',
      genreRPG: 'Role-playing (RPG)',
      genreShooter: 'Shooter',
      genreSimulator: 'Simulator',
      genreStrategy: 'Strategy',
      genreTBS: 'Turn-based strategy (TBS)',
      newItemMessage: 'New item was added',
      deleteItemMessage: 'Selected items were deleted',
      deleteDialogHeader: 'Do you want to delete selected items?',
      deleteDialogMessage: 'Do you really want to remove selected items from the list? They will be removed immediately and will not be restored.',
      deleteDialogDisagree: 'Cancel',
      deleteDialogAgree: 'Agree',
      mutateItemMessage: 'Selected item was mutated',
      mutateItemMessageFail: 'Changes were not saved. No connection to DB!',
      viewSwitcherdescriptionON: 'Back to Table View',
      viewSwitcherdescriptionOFF: 'Switch to Chart View',
      chartMainTitle: 'Games amount by genre',
      chartXcatTitle: 'Genres',
      chartYcatTitle: 'Games Amount',
      barLabel: 'Game amount',
    },
  },
}

export default enLocale
