const ruLocale = {
  translation: {
    description: {
      h1: 'СПИСОК ЛЮБИМЫХ КОМПЬЮТЕРНЫХ ИГР',
      loading: 'Пожалуйста подождите. Загрузка данных...',
      gameTitleInput: 'Название игры',
      gameTitlePlaceholder: 'Игра',
      yearInput: 'Год',
      genreInput: 'Жанр',
      genrePlaceholder: '--Выбор жанра--',
      raitingInput: 'Рейтинг',
      developerInput: 'Разработчик',
      developerPlaceholder: 'Разработчик',
      publisherInput: 'Издатель',
      publisherPlaceholder: 'если несколько - через запятые',
      buttonAdd: '+ВВОД',
      buttonDelete: 'УДАЛИТЬ',
      genreArcade: 'Аркада',
      genreAdventure: 'Приключения',
      genreFighting: 'Файтинг',
      genreRacing: 'Гонки',
      genreRTS: 'Стратегия в реальном времени',
      genreRPG: 'Ролевая игра',
      genreShooter: 'Шутер',
      genreSimulator: 'Симулятор',
      genreStrategy: 'Стратегия',
      genreTBS: 'Пошаговая стратегия',
      newItemMessage: 'Добавлен новый элемент',
      deleteDialogHeader: 'Хотите удалить выделенные элементы?',
      deleteItemMessage: 'Выбранные элементы были удалены',
      deleteDialogMessage: 'Вы действительно хотите удалить выделенные элементы из списка? Они будут удалены немедленно и не смогут быть востановленны.',
      deleteDialogDisagree: 'Отмена',
      deleteDialogAgree: 'Да',
      mutateItemMessage: 'Выделенный элемент был изменен',
      mutateItemMessageFail: 'Изменения не были сохранены. Нет соединения с БД!',
    },
  },
}

export default ruLocale
